AWSTemplateFormatVersion: '2010-09-09'
Description: Tools Index
Parameters:
  ACMCertArn:
    Description: ACM certificate ARN for CloudFront
    Type: String
  Domain:
    Description: gutools.co.uk sub-domain to serve
    Type: String
Resources:
  StaticContentBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: "Retain"
    Properties:
      BucketName: "tools-gutools-co-uk"
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: "index.html"
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
            - GET
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
  StaticContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: StaticContentBucket
      PolicyDocument:
        Id: ToolsIndexdBucketPolicy
        Statement:
        - Action: ['s3:GetObject']
          Effect: Allow
          Principal: "*"
          Resource:
            Fn::Join: ['', ['arn:aws:s3:::', {Ref: StaticContentBucket}, '/*' ]]
  CFDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref 'Domain'
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: "false"
          TargetOriginId: "tools-index"
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: "index.html"
        Enabled: "true"
        Origins:
        - DomainName:
            Fn::Join: ['', [{Ref: StaticContentBucket}, '.s3.amazonaws.com' ]]
          Id: "tools-index"
          CustomOriginConfig:
            OriginProtocolPolicy: https-only
        ViewerCertificate:
          AcmCertificateArn: !Ref 'ACMCertArn'
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
  CircleCIUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: CircleCIPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:ListBucket"
                  - "s3:ListObjects"
                  - "s3:DeleteObject"
                Resource:
                  - Fn::Join: ['', ['arn:aws:s3:::', {Ref: StaticContentBucket} ]]
                  - Fn::Join: ['', ['arn:aws:s3:::', {Ref: StaticContentBucket}, '/*' ]]
  CircleCIKeys:
      Type: "AWS::IAM::AccessKey"
      Properties:
        UserName: {"Ref": "CircleCIUser"}
        Serial: 1
Outputs:
  CircleCIAWSID:
    Value:
      Ref: "CircleCIKeys"
  CircleCIAWSSecret:
    Value:
      Fn::GetAtt: ["CircleCIKeys", "SecretAccessKey"]
