AWSTemplateFormatVersion: '2010-09-09'
Description: Tools Index
Parameters:
  WhitelistedIp:
    Type: String
    Description: IP range for the office
    Default: 77.91.248.0/21
  ToolsIndexUri:
    Type: String
    Description: URI of the Tools index page
    Default: tools.gutools.co.uk
Resources:
  ToolsIndexBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: "Retain"
    Properties:
      BucketName: {Ref: ToolsIndexUri}
      AccessControl: Private
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: {Ref: ToolsIndexUri}
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
            - GET
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
  ToolsIndexdBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: ToolsIndexBucket
      PolicyDocument:
        Id: ToolsIndexdBucketPolicy
        Statement:
        - Action: ['s3:GetObject']
          Effect: Allow
          Principal: "*"
          Resource:
            Fn::Join: ['', ['arn:aws:s3:::', {Ref: ToolsIndexBucket}, '/*' ]]
          Condition:
            IpAddress:
              aws:SourceIp:
              - {Ref: WhitelistedIp}
