AWSTemplateFormatVersion: '2010-09-09'
Description: Tools Index
Parameters:
  WhitelistedIp:
    Type: String
    Description: IP range for the office
    Default: 77.91.248.0/21
Resources:
  ToolsIndexBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: "Retain"
    Properties:
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: "index.html"
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
            - GET
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
  ToolsIndexdBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: ToolsIndexBucket
      PolicyDocument:
        Id: ToolsIndexdBucketPolicy
        Statement:
        - Action: ['s3:GetObject']
          Effect: Allow
          Principal: "*"
          Resource:
            Fn::Join: ['', ['arn:aws:s3:::', {Ref: ToolsIndexBucket}, '/*' ]]
          Condition:
            IpAddress:
              aws:SourceIp:
              - {Ref: WhitelistedIp}
  CircleCIUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: CircleCIPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                  - "s3:ListBucket"
                  - "s3:GetBucketLocation"
                  - "s3:DeleteObject"
                Resource:
                  Fn::Join: ['', ['arn:aws:s3:::', {Ref: ToolsIndexBucket}, '/*' ]]
  CircleCIKeys:
      Type: "AWS::IAM::AccessKey"
      Properties:
        UserName: {"Ref": "CircleCIUser"}
        Serial: 1
Outputs:
  CircleCIAWSID:
    Value:
      Ref: "CircleCIKeys"
  CircleCIAWSSecret:
    Value:
      Fn::GetAtt: ["CircleCIKeys", "SecretAccessKey"]
